--liquibase formatted sql
--changeset edvan.ronchi:1 context:test,prod
CREATE TABLE PICPAY.USERS(
    ID NUMERIC(19,0) PRIMARY KEY,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    BALANCE NUMERIC(9,0) DEFAULT 0,
    DOCUMENT VARCHAR(20) NOT NULL UNIQUE,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    TYPE VARCHAR(20) DEFAULT 'COMMON' NOT NULL
);
--rollback DROP TABLE PICPAY.USERS;

--changeset edvan.ronchi:2 context:test,prod
COMMENT ON COLUMN PICPAY.USERS.ID IS 'Identifier';
COMMENT ON COLUMN PICPAY.USERS.FIRST_NAME IS 'First name';
COMMENT ON COLUMN PICPAY.USERS.LAST_NAME IS 'Last name';
COMMENT ON COLUMN PICPAY.USERS.PASSWORD IS 'Password';
COMMENT ON COLUMN PICPAY.USERS.BALANCE IS 'Account balance';
COMMENT ON COLUMN PICPAY.USERS.DOCUMENT IS 'Document number';
COMMENT ON COLUMN PICPAY.USERS.EMAIL IS 'E-mail';
COMMENT ON COLUMN PICPAY.USERS.TYPE IS 'Account Type';
--rollback not required

--changeset edvan.ronchi:3 context:prod
CREATE SEQUENCE PICPAY.SEQ_USERS MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1;
--rollback DROP SEQUENCE PICPAY.SEQ_USERS;
